version: '3.6'
services:
  dnsmasq:
    build:
      context: .
    volumes:
    - .:/go/src/github.com/tomoyamachi/go-dnsmasq
    environment:
      - LOG_LEVEL=debug
      - DNSMASQ_HOSTSFILE="./hosts"
    command: [ "/usr/bin/tail" ,"-f", "/dev/null" ]
    # go run $(pwd)/cmd/dnsmasq -h
  request:
    build:
      context: ./develop/request